name: Clean up Imports

on:
  pull_request:
    branches:
    - master
    paths:
    - 'src/main/java/**'

jobs:
  build:

    name: Clean up Imports
    runs-on: ubuntu-latest
    if: $ {{ secrets.ACCESS_TOKEN }} != null

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Clean up Imports
      uses: axel-op/googlejavaformat-action@v3.3.2
      with:
        files: '**/*.java'
        skipCommit: false
        args: "--fix-imports-only --replace"
        githubToken: $ {{ secrets.ACCESS_TOKEN }}
